# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsed < Formula
  desc "command line JSON editor"
  homepage "https://github.com/farzadmf/jsed"
  version "0.2"

  on_macos do
    url "https://github.com/farzadmf/jsed/releases/download/v0.2/jsed_0.2_darwin_all.tar.gz"
    sha256 "929647e4bda2caaaad2b323a57412b79eabdd4133077be344db7870e5c92cf3a"

    def install
      bin.install "jsed"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/farzadmf/jsed/releases/download/v0.2/jsed_0.2_linux_arm64.tar.gz"
      sha256 "be1d798f4620ef94b7bdf3571cc6dc84e222d9b8a2e08080d5989485ffd009e3"

      def install
        bin.install "jsed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/farzadmf/jsed/releases/download/v0.2/jsed_0.2_linux_amd64.tar.gz"
      sha256 "e148323361446673f40733238c74d4a3bf0d457d5365886f0b423d9d353ed26f"

      def install
        bin.install "jsed"
      end
    end
  end
end
