# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc "command line JSON editor"
  homepage "https://github.com/farzadmf/jsed"
  version "0.1"

  on_macos do
    url "https://github.com/farzadmf/jsed/releases/download/v0.1/jsed_0.1_darwin_all.tar.gz"
    sha256 "14f237ded35490c5ee53811bc74140d30e509f803a24f88a5fd612ab0e8f112a"

    def install
      bin.install "jsed"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/farzadmf/jsed/releases/download/v0.1/jsed_0.1_linux_arm64.tar.gz"
      sha256 "966495acf86e6ee5a2a88a208c4521b46a26fd4bf4f57ee3615f9ef7af635fbb"

      def install
        bin.install "jsed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/farzadmf/jsed/releases/download/v0.1/jsed_0.1_linux_amd64.tar.gz"
      sha256 "ca4170c907f591c109c250bf575ab9fb37543972ce72194df1e82faa43e01db9"

      def install
        bin.install "jsed"
      end
    end
  end
end
